openapi: 3.0.0
servers:
  - url: 'http://localhost:4003'
info:
  description: a rating service
  version: 1.0.0
  title: Rating Service
tags:
  - name: rating
    description: Operations about rating
paths:
  /rating:
    post:
      tags:
        - rating
      summary: Create rating
      operationId: createRating
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRating'
          description: Created rating object
          required: true
    get:
      tags:
        - rating
      summary: List ratings
      description: a list of ratings
      operationId: listRatings
      parameters:
        - name: postId
          in: query
          description: Only get ratings of the supplied post
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatingList'
        '400':
          description: invalid post id
        '404':
          description: Rating not found
  '/rating/{id}':
    get:
      tags:
        - rating
      summary: Get rating by id
      description: ''
      operationId: getRatingById
      parameters:
        - name: id
          in: path
          description: The id that needs to be fetched. Use 0 for testing.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
        '400':
          description: Invalid id supplied
        '404':
          description: Rating not found
    delete:
      tags:
        - rating
      summary: Delete rating
      description: Delete a rating by id
      operationId: deleteRating
      parameters:
        - name: id
          in: path
          description: The id that needs to be deleted. Use 0 for testing.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid id supplied
        '404':
          description: Rating not found
components:
  schemas:
    Rating:
      title: a Rating
      description: A Rating
      type: object
      properties:
        id:
          type: integer
          format: int64
        postId:
          type: integer
          format: int64
        value:
          type: integer
          format: int32
    RatingList:
      title: List Ratings
      description: a list of ratings
      type: object
      properties:
        ratings:
          type: "array"
          items:
            $ref: '#/components/schemas/Rating'
    CreateRating:
      title: create rating body
      description: create rating body
      type: object
      properties:
        postId:
          type: integer
          format: int64
        rating:
          type: integer
          format: int32
        
    