openapi: 3.0.0
servers:
  - url: 'http://localhost:4002'
info:
  description: a post service
  version: 1.0.0
  title: Post Service
tags:
  - name: post
    description: Operations about post
paths:
  /post:
    post:
      tags:
        - post
      summary: Create post
      description: This can only be done by the logged in post.
      operationId: createPost
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePost'
          description: Created post object
          required: true
    get:
      tags:
        - post
      summary: List posts
      description: a list of posts
      operationId: listPosts
      parameters:
        - name: authorId
          in: query
          description: Only get post of the supplied author
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostList'
        '400':
          description: invalid author id
        '404':
          description: Post not found
  '/post/{id}':
    get:
      tags:
        - post
      summary: Get post by id
      description: ''
      operationId: getPostById
      parameters:
        - name: id
          in: path
          description: The id that needs to be fetched. Use 0 for testing.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Invalid id supplied
        '404':
          description: Post not found
    delete:
      tags:
        - post
      summary: Delete post
      description: Delete a post by id
      operationId: deletePost
      parameters:
        - name: id
          in: path
          description: The id that needs to be deleted. Use 0 for testing.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid id supplied
        '404':
          description: Post not found
components:
  schemas:
    Post:
      title: a Post
      description: A Post
      type: object
      properties:
        id:
          type: integer
          format: int64
        authorId:
          type: integer
          format: int64
        headline:
          type: string
        content:
          type: string
          description: content as markdown
    PostList:
      title: List Posts
      description: a list of posts
      type: object
      properties:
        posts:
          type: "array"
          items:
            $ref: '#/components/schemas/Post'
    CreatePost:
      title: create post body
      description: create post body
      type: object
      properties:
        authorId:
          type: integer
          format: int64
        headline:
          type: string
        content:
          type: string
          description: content as markdown
        
    